version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "thursday"
    open-pull-requests-limit: 100
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    # Exclude configs synced from upstream prometheus/prometheus.
    exclude-paths:
      - .github/workflows/container_description.yml
      - .github/workflows/golangci-lint.yml
      - .github/workflows/govulncheck.yml
      - .github/workflows/scorecards.yml
      - .github/workflows/stale.yml
