FROM openjdk:17-jdk-bullseye as builder

RUN jlink \
        --add-modules java.base,java.desktop,java.logging,java.management,java.naming,jdk.unsupported \
        --strip-debug \
        --no-man-pages \
        --no-header-files \
        --compress=2 \
        --output /javaruntime


FROM debian:bullseye-slim as runner
LABEL maintainer="The Prometheus Authors <prometheus-developers@googlegroups.com>"
EXPOSE 9106

ENV JAVA_HOME=/opt/java/openjdk
ENV PATH=${JAVA_HOME}/bin:${PATH}

WORKDIR /
RUN mkdir /config
COPY cloudwatch_exporter.jar /cloudwatch_exporter.jar
COPY --from=builder /javaruntime $JAVA_HOME
ENTRYPOINT [ "java", "-jar", "/cloudwatch_exporter.jar", "9106"]
CMD ["/config/config.yml"]
