{
 "title": "AWS DocumentDB",
 "description": "AWS documentDB dashboard from cloudwatch exporter",
 "tags": [
  "DocumendDB",
  "MongoDB"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbinstance_identifier",
    "query": "label_values(aws_docdb_cpuutilization_average, dbinstance_identifier)"
   }
  ]
 },
 "panels": [
  {
   "title": "Database cursors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aws_docdb_database_cursors_average{dbinstance_identifier=\"$dbinstance_identifier\"}) by (dbinstance_identifier)",
     "legendFormat": "database_cursors"
    }
   ]
  },
  {
   "title": "Cpu Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aws_docdb_cpuutilization_average{dbinstance_identifier=\"$dbinstance_identifier\"}) by (dbinstance_identifier)",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Free Storage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aws_docdb_free_local_storage_average{dbinstance_identifier=\"$dbinstance_identifier\"}) by (dbinstance_identifier)",
     "legendFormat": "GB"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aws_docdb_freeable_memory_average{dbinstance_identifier=\"$dbinstance_identifier\"}) by (dbinstance_identifier)",
     "legendFormat": "GB"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aws_docdb_read_latency_average{dbinstance_identifier=\"$dbinstance_identifier\"}) by (dbinstance_identifier)",
     "legendFormat": "ms"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aws_docdb_write_latency_average{dbinstance_identifier=\"$dbinstance_identifier\"}) by (dbinstance_identifier)",
     "legendFormat": "ms"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_docdb_database_connections_maximum{dbinstance_identifier=\"$dbinstance_identifier\"}) by (dbinstance_identifier)",
     "legendFormat": "database_connections"
    }
   ]
  },
  {
   "title": "Database Cursors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_docdb_database_cursors_average{dbinstance_identifier=\"$dbinstance_identifier\"}) by (dbinstance_identifier)",
     "legendFormat": "database_cursors"
    },
    {
     "expr": "sum(aws_docdb_database_cursors_max_average{dbinstance_identifier=\"$dbinstance_identifier\"}) by (dbinstance_identifier)",
     "legendFormat": "database_cursors_max"
    }
   ]
  },
  {
   "title": "Cpu Utilization %",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(aws_docdb_cpuutilization_average{dbinstance_identifier=\"$dbinstance_identifier\"}) by (dbinstance_identifier)"
    }
   ]
  },
  {
   "title": "Freeable Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(aws_docdb_freeable_memory_average{dbinstance_identifier=\"$dbinstance_identifier\"}) by (dbinstance_identifier)",
     "legendFormat": "freeable_memory"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_docdb_index_buffer_cache_hit_ratio_average{dbinstance_identifier=\"$dbinstance_identifier\"}) by (dbinstance_identifier)",
     "legendFormat": "index_buffer_cache_hit_ratio"
    },
    {
     "expr": "sum(aws_docdb_buffer_cache_hit_ratio_average{dbinstance_identifier=\"$dbinstance_identifier\"}) by (dbinstance_identifier)",
     "legendFormat": "buffer_cache_hit_ratio"
    }
   ]
  },
  {
   "title": "Free Local Storage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(aws_docdb_free_local_storage_average{dbinstance_identifier=\"$dbinstance_identifier\"}) by (dbinstance_identifier)",
     "legendFormat": "free_local_storage"
    }
   ]
  },
  {
   "title": "Disk Queue Depth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_docdb_disk_queue_depth_average{dbinstance_identifier=\"$dbinstance_identifier\"}) by (dbinstance_identifier)",
     "legendFormat": "disk_queue_depth"
    }
   ]
  },
  {
   "title": "Throughtput",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(aws_docdb_read_throughput_average{dbinstance_identifier=\"$dbinstance_identifier\"}) by (dbinstance_identifier)",
     "legendFormat": "read_throughput"
    },
    {
     "expr": "sum(aws_docdb_write_throughput_average{dbinstance_identifier=\"$dbinstance_identifier\"}) by (dbinstance_identifier)",
     "legendFormat": "write_throughput"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(aws_docdb_read_latency_average{dbinstance_identifier=\"$dbinstance_identifier\"}) by (dbinstance_identifier)",
     "legendFormat": "read_latency"
    },
    {
     "expr": "sum(aws_docdb_write_latency_average{dbinstance_identifier=\"$dbinstance_identifier\"}) by (dbinstance_identifier)",
     "legendFormat": "write_latency"
    }
   ]
  },
  {
   "title": "Operation Opcounters",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_docdb_opcounters_command_average{dbinstance_identifier=\"$dbinstance_identifier\"}) by (dbinstance_identifier)",
     "legendFormat": "opcounters_command"
    },
    {
     "expr": "sum(aws_docdb_opcounters_delete_average{dbinstance_identifier=\"$dbinstance_identifier\"}) by (dbinstance_identifier)",
     "legendFormat": "opcounters_delete"
    },
    {
     "expr": "sum(aws_docdb_opcounters_getmore_average{dbinstance_identifier=\"$dbinstance_identifier\"}) by (dbinstance_identifier)",
     "legendFormat": "opcounters_getmore"
    },
    {
     "expr": "sum(aws_docdb_opcounters_update_average{dbinstance_identifier=\"$dbinstance_identifier\"}) by (dbinstance_identifier)",
     "legendFormat": "opcounters_update"
    }
   ]
  }
 ]
}